// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyCMS.Web.Areas.Admin.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Admin.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string TinyMCE = "TinyMCE";
            public readonly string IFrame = "IFrame";
            public readonly string Standalone = "Standalone";
            public readonly string TopMenu = "TopMenu";
            public readonly string Footer = "Footer";
            public readonly string QuickSidebar = "QuickSidebar";
            public readonly string Sidebar = "Sidebar";
            public readonly string Breadcrumb = "Breadcrumb";
            public readonly string RenderDashBoard = "RenderDashBoard";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string TinyMCE = "TinyMCE";
            public const string IFrame = "IFrame";
            public const string Standalone = "Standalone";
            public const string TopMenu = "TopMenu";
            public const string Footer = "Footer";
            public const string QuickSidebar = "QuickSidebar";
            public const string Sidebar = "Sidebar";
            public const string Breadcrumb = "Breadcrumb";
            public const string RenderDashBoard = "RenderDashBoard";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Breadcrumb = "_Breadcrumb";
                public readonly string _DashBoard = "_DashBoard";
                public readonly string _Footer = "_Footer";
                public readonly string _QuickSidebar = "_QuickSidebar";
                public readonly string _Sidebar = "_Sidebar";
                public readonly string _TopMenu = "_TopMenu";
                public readonly string _UserStatus = "_UserStatus";
                public readonly string IFrame = "IFrame";
                public readonly string Index = "Index";
                public readonly string IndexPHP = "IndexPHP";
                public readonly string Standalone = "Standalone";
                public readonly string TinyMCE = "TinyMCE";
            }
            public readonly string _Breadcrumb = "~/Areas/Admin/Views/Home/_Breadcrumb.cshtml";
            public readonly string _DashBoard = "~/Areas/Admin/Views/Home/_DashBoard.cshtml";
            public readonly string _Footer = "~/Areas/Admin/Views/Home/_Footer.cshtml";
            public readonly string _QuickSidebar = "~/Areas/Admin/Views/Home/_QuickSidebar.cshtml";
            public readonly string _Sidebar = "~/Areas/Admin/Views/Home/_Sidebar.cshtml";
            public readonly string _TopMenu = "~/Areas/Admin/Views/Home/_TopMenu.cshtml";
            public readonly string _UserStatus = "~/Areas/Admin/Views/Home/_UserStatus.cshtml";
            public readonly string IFrame = "~/Areas/Admin/Views/Home/IFrame.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Home/Index.cshtml";
            public readonly string IndexPHP = "~/Areas/Admin/Views/Home/IndexPHP.php";
            public readonly string Standalone = "~/Areas/Admin/Views/Home/Standalone.cshtml";
            public readonly string TinyMCE = "~/Areas/Admin/Views/Home/TinyMCE.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : MyCMS.Web.Areas.Admin.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TinyMCEOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TinyMCE()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TinyMCE);
            TinyMCEOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IFrameOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IFrame()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IFrame);
            IFrameOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StandaloneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Standalone()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Standalone);
            StandaloneOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TopMenuOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopMenu()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopMenu);
            TopMenuOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FooterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Footer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Footer);
            FooterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void QuickSidebarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult QuickSidebar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuickSidebar);
            QuickSidebarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SidebarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Sidebar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Sidebar);
            SidebarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BreadcrumbOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Breadcrumb()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Breadcrumb);
            BreadcrumbOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RenderDashBoardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RenderDashBoard()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RenderDashBoard);
            RenderDashBoardOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
