// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyCMS.Web.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string IFrame = "IFrame";
            public readonly string Standalone = "Standalone";
            public readonly string BooksList = "BooksList";
            public readonly string Breadcrumb = "Breadcrumb";
            public readonly string Slider = "Slider";
            public readonly string Telegram = "Telegram";
            public readonly string FooterContactInfo = "FooterContactInfo";
            public readonly string FooterSocialNetwork = "FooterSocialNetwork";
            public readonly string NavBar = "NavBar";
            public readonly string NavbarItems = "NavbarItems";
            public readonly string Announce = "Announce";
            public readonly string SiteMapXml = "SiteMapXml";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string IFrame = "IFrame";
            public const string Standalone = "Standalone";
            public const string BooksList = "BooksList";
            public const string Breadcrumb = "Breadcrumb";
            public const string Slider = "Slider";
            public const string Telegram = "Telegram";
            public const string FooterContactInfo = "FooterContactInfo";
            public const string FooterSocialNetwork = "FooterSocialNetwork";
            public const string NavBar = "NavBar";
            public const string NavbarItems = "NavbarItems";
            public const string Announce = "Announce";
            public const string SiteMapXml = "SiteMapXml";
        }


        static readonly ActionParamsClass_BooksList s_params_BooksList = new ActionParamsClass_BooksList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BooksList BooksListParams { get { return s_params_BooksList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BooksList
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Announce = "_Announce";
                public readonly string _BooksList = "_BooksList";
                public readonly string _Breadcrumb = "_Breadcrumb";
                public readonly string _FooterContactInfo = "_FooterContactInfo";
                public readonly string _FooterSocialNetwork = "_FooterSocialNetwork";
                public readonly string _NavBar = "_NavBar";
                public readonly string _NavBarItems = "_NavBarItems";
                public readonly string _Slider = "_Slider";
                public readonly string _Telegram = "_Telegram";
                public readonly string IFrame = "IFrame";
                public readonly string Index = "Index";
                public readonly string IndexPHP = "IndexPHP";
                public readonly string Standalone = "Standalone";
            }
            public readonly string _Announce = "~/Views/Home/_Announce.cshtml";
            public readonly string _BooksList = "~/Views/Home/_BooksList.cshtml";
            public readonly string _Breadcrumb = "~/Views/Home/_Breadcrumb.cshtml";
            public readonly string _FooterContactInfo = "~/Views/Home/_FooterContactInfo.cshtml";
            public readonly string _FooterSocialNetwork = "~/Views/Home/_FooterSocialNetwork.cshtml";
            public readonly string _NavBar = "~/Views/Home/_NavBar.cshtml";
            public readonly string _NavBarItems = "~/Views/Home/_NavBarItems.cshtml";
            public readonly string _Slider = "~/Views/Home/_Slider.cshtml";
            public readonly string _Telegram = "~/Views/Home/_Telegram.cshtml";
            public readonly string IFrame = "~/Views/Home/IFrame.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string IndexPHP = "~/Views/Home/IndexPHP.php";
            public readonly string Standalone = "~/Views/Home/Standalone.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : MyCMS.Web.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IFrameOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IFrame()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IFrame);
            IFrameOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StandaloneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Standalone()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Standalone);
            StandaloneOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BooksListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult BooksList(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BooksList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            BooksListOverride(callInfo, page, count);
            return callInfo;
        }

        [NonAction]
        partial void BreadcrumbOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Breadcrumb()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Breadcrumb);
            BreadcrumbOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SliderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Slider()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Slider);
            SliderOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void TelegramOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Telegram()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Telegram);
            TelegramOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FooterContactInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FooterContactInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FooterContactInfo);
            FooterContactInfoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FooterSocialNetworkOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FooterSocialNetwork()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FooterSocialNetwork);
            FooterSocialNetworkOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NavBarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NavBar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NavBar);
            NavBarOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NavbarItemsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NavbarItems()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NavbarItems);
            NavbarItemsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AnnounceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Announce()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Announce);
            AnnounceOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SiteMapXmlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SiteMapXml()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SiteMapXml);
            SiteMapXmlOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
