// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MyCMS.Web.Controllers
{
    public partial class PostController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PostController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Like()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Like);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DisLike()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisLike);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SilmilarPosts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SilmilarPosts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UserPosts()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserPosts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UserPostsList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserPostsList);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PostController Actions { get { return MVC.Post; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Post";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Post";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Like = "Like";
            public readonly string DisLike = "DisLike";
            public readonly string SilmilarPosts = "SilmilarPosts";
            public readonly string SimilarPostList = "SimilarPostList";
            public readonly string PostList = "PostList";
            public readonly string KnowledgeBase = "KnowledgeBase";
            public readonly string LastPost = "LastPost";
            public readonly string SidePostsWithSkip = "SidePostsWithSkip";
            public readonly string FooterPostsWithSkip = "FooterPostsWithSkip";
            public readonly string LatestPost = "LatestPost";
            public readonly string FooterLatestPost = "FooterLatestPost";
            public readonly string SideLatestPost = "SideLatestPost";
            public readonly string SidePopularPost = "SidePopularPost";
            public readonly string UserPosts = "UserPosts";
            public readonly string UserPostsList = "UserPostsList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Like = "Like";
            public const string DisLike = "DisLike";
            public const string SilmilarPosts = "SilmilarPosts";
            public const string SimilarPostList = "SimilarPostList";
            public const string PostList = "PostList";
            public const string KnowledgeBase = "KnowledgeBase";
            public const string LastPost = "LastPost";
            public const string SidePostsWithSkip = "SidePostsWithSkip";
            public const string FooterPostsWithSkip = "FooterPostsWithSkip";
            public const string LatestPost = "LatestPost";
            public const string FooterLatestPost = "FooterLatestPost";
            public const string SideLatestPost = "SideLatestPost";
            public const string SidePopularPost = "SidePopularPost";
            public const string UserPosts = "UserPosts";
            public const string UserPostsList = "UserPostsList";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Like s_params_Like = new ActionParamsClass_Like();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Like LikeParams { get { return s_params_Like; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Like
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DisLike s_params_DisLike = new ActionParamsClass_DisLike();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DisLike DisLikeParams { get { return s_params_DisLike; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DisLike
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SilmilarPosts s_params_SilmilarPosts = new ActionParamsClass_SilmilarPosts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SilmilarPosts SilmilarPostsParams { get { return s_params_SilmilarPosts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SilmilarPosts
        {
            public readonly string id = "id";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_SimilarPostList s_params_SimilarPostList = new ActionParamsClass_SimilarPostList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SimilarPostList SimilarPostListParams { get { return s_params_SimilarPostList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SimilarPostList
        {
            public readonly string labelId = "labelId";
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_PostList s_params_PostList = new ActionParamsClass_PostList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PostList PostListParams { get { return s_params_PostList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PostList
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_KnowledgeBase s_params_KnowledgeBase = new ActionParamsClass_KnowledgeBase();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_KnowledgeBase KnowledgeBaseParams { get { return s_params_KnowledgeBase; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_KnowledgeBase
        {
            public readonly string page = "page";
            public readonly string count = "count";
            public readonly string skip = "skip";
        }
        static readonly ActionParamsClass_SidePostsWithSkip s_params_SidePostsWithSkip = new ActionParamsClass_SidePostsWithSkip();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SidePostsWithSkip SidePostsWithSkipParams { get { return s_params_SidePostsWithSkip; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SidePostsWithSkip
        {
            public readonly string page = "page";
            public readonly string count = "count";
            public readonly string skip = "skip";
        }
        static readonly ActionParamsClass_FooterPostsWithSkip s_params_FooterPostsWithSkip = new ActionParamsClass_FooterPostsWithSkip();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FooterPostsWithSkip FooterPostsWithSkipParams { get { return s_params_FooterPostsWithSkip; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FooterPostsWithSkip
        {
            public readonly string page = "page";
            public readonly string count = "count";
            public readonly string skip = "skip";
        }
        static readonly ActionParamsClass_LatestPost s_params_LatestPost = new ActionParamsClass_LatestPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LatestPost LatestPostParams { get { return s_params_LatestPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LatestPost
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_FooterLatestPost s_params_FooterLatestPost = new ActionParamsClass_FooterLatestPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FooterLatestPost FooterLatestPostParams { get { return s_params_FooterLatestPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FooterLatestPost
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_SideLatestPost s_params_SideLatestPost = new ActionParamsClass_SideLatestPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SideLatestPost SideLatestPostParams { get { return s_params_SideLatestPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SideLatestPost
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_SidePopularPost s_params_SidePopularPost = new ActionParamsClass_SidePopularPost();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SidePopularPost SidePopularPostParams { get { return s_params_SidePopularPost; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SidePopularPost
        {
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_UserPosts s_params_UserPosts = new ActionParamsClass_UserPosts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserPosts UserPostsParams { get { return s_params_UserPosts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserPosts
        {
            public readonly string userName = "userName";
            public readonly string page = "page";
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_UserPostsList s_params_UserPostsList = new ActionParamsClass_UserPostsList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserPostsList UserPostsListParams { get { return s_params_UserPostsList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserPostsList
        {
            public readonly string userName = "userName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _FooterLatestPost = "_FooterLatestPost";
                public readonly string _FooterPostsWithSkip = "_FooterPostsWithSkip";
                public readonly string _LastPost = "_LastPost";
                public readonly string _LatestPost = "_LatestPost";
                public readonly string _SideLatestPost = "_SideLatestPost";
                public readonly string _SidePopularPost = "_SidePopularPost";
                public readonly string _SidePostsWithSkip = "_SidePostsWithSkip";
                public readonly string _SimilarPostList = "_SimilarPostList";
                public readonly string _SimilarPosts = "_SimilarPosts";
                public readonly string _UserPosts = "_UserPosts";
                public readonly string Index = "Index";
                public readonly string knowledgeBase = "knowledgeBase";
                public readonly string PostList = "PostList";
                public readonly string UserPostsList = "UserPostsList";
            }
            public readonly string _FooterLatestPost = "~/Views/Post/_FooterLatestPost.cshtml";
            public readonly string _FooterPostsWithSkip = "~/Views/Post/_FooterPostsWithSkip.cshtml";
            public readonly string _LastPost = "~/Views/Post/_LastPost.cshtml";
            public readonly string _LatestPost = "~/Views/Post/_LatestPost.cshtml";
            public readonly string _SideLatestPost = "~/Views/Post/_SideLatestPost.cshtml";
            public readonly string _SidePopularPost = "~/Views/Post/_SidePopularPost.cshtml";
            public readonly string _SidePostsWithSkip = "~/Views/Post/_SidePostsWithSkip.cshtml";
            public readonly string _SimilarPostList = "~/Views/Post/_SimilarPostList.cshtml";
            public readonly string _SimilarPosts = "~/Views/Post/_SimilarPosts.cshtml";
            public readonly string _UserPosts = "~/Views/Post/_UserPosts.cshtml";
            public readonly string Index = "~/Views/Post/Index.cshtml";
            public readonly string knowledgeBase = "~/Views/Post/knowledgeBase.cshtml";
            public readonly string PostList = "~/Views/Post/PostList.cshtml";
            public readonly string UserPostsList = "~/Views/Post/UserPostsList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PostController : MyCMS.Web.Controllers.PostController
    {
        public T4MVC_PostController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            IndexOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LikeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Like(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Like);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LikeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DisLikeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DisLike(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DisLike);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DisLikeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SilmilarPostsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult SilmilarPosts(int id, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SilmilarPosts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            SilmilarPostsOverride(callInfo, id, count);
            return callInfo;
        }

        [NonAction]
        partial void SimilarPostListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int labelId, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult SimilarPostList(int labelId, int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SimilarPostList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "labelId", labelId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            SimilarPostListOverride(callInfo, labelId, page, count);
            return callInfo;
        }

        [NonAction]
        partial void PostListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult PostList(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PostList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            PostListOverride(callInfo, page, count);
            return callInfo;
        }

        [NonAction]
        partial void KnowledgeBaseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count, int skip);

        [NonAction]
        public override System.Web.Mvc.ActionResult KnowledgeBase(int page, int count, int skip)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.KnowledgeBase);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "skip", skip);
            KnowledgeBaseOverride(callInfo, page, count, skip);
            return callInfo;
        }

        [NonAction]
        partial void LastPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LastPost()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LastPost);
            LastPostOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SidePostsWithSkipOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count, int skip);

        [NonAction]
        public override System.Web.Mvc.ActionResult SidePostsWithSkip(int page, int count, int skip)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SidePostsWithSkip);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "skip", skip);
            SidePostsWithSkipOverride(callInfo, page, count, skip);
            return callInfo;
        }

        [NonAction]
        partial void FooterPostsWithSkipOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count, int skip);

        [NonAction]
        public override System.Web.Mvc.ActionResult FooterPostsWithSkip(int page, int count, int skip)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FooterPostsWithSkip);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "skip", skip);
            FooterPostsWithSkipOverride(callInfo, page, count, skip);
            return callInfo;
        }

        [NonAction]
        partial void LatestPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult LatestPost(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LatestPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            LatestPostOverride(callInfo, page, count);
            return callInfo;
        }

        [NonAction]
        partial void FooterLatestPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult FooterLatestPost(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FooterLatestPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            FooterLatestPostOverride(callInfo, page, count);
            return callInfo;
        }

        [NonAction]
        partial void SideLatestPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult SideLatestPost(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SideLatestPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            SideLatestPostOverride(callInfo, page, count);
            return callInfo;
        }

        [NonAction]
        partial void SidePopularPostOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult SidePopularPost(int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SidePopularPost);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            SidePopularPostOverride(callInfo, page, count);
            return callInfo;
        }

        [NonAction]
        partial void UserPostsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName, int page, int count);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserPosts(string userName, int page, int count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserPosts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            UserPostsOverride(callInfo, userName, page, count);
            return callInfo;
        }

        [NonAction]
        partial void UserPostsListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserPostsList(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserPostsList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            UserPostsListOverride(callInfo, userName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
